// Health Book ---------------------------------------------

export const HANDLE_INPUT_CHANGE = 'handleInputChange';

export const GET_INTERNAL_USER_LOGIN_TOKEN = 'get_Internal_User_Login_Token';
export const GET_TOKEN_REQUESTED = 'GET_TOKEN_REQUESTED';
export const GET_TOKEN_SUCESS = 'GET_TOKEN_SUCESS';
export const GET_TOKEN_FAILED = 'GET_TOKEN_FAILED';

export const CREATE_CATEGORY_REQUESTED = 'CREATE_CATEGORY_REQUESTED';
export const CREATE_CATEGORY_SUCESS = 'CREATE_CATEGORY_SUCESS';
export const CREATE_CATEGORY_FAILED = 'CREATE_CATEGORY_FAILED';

export const TEST_CATEGORY_REQUESTED = 'TEST_CATEGORY_REQUESTED';
export const TEST_CATEGORY_SUCESS = 'TEST_CATEGORY_SUCESS';
export const TEST_CATEGORY_FAILED = 'TEST_CATEGORY_FAILED';

export const MEDICAL_TEST_RESULT_TYPE_REQUESTED = 'MEDICAL_TEST_RESULT_TYPE_REQUESTED';
export const MEDICAL_TEST_RESULT_TYPE_SUCESS = 'MEDICAL_TEST_RESULT_TYPE_SUCESS';
export const MEDICAL_TEST_RESULT_TYPE_FAILED = 'MEDICAL_TEST_RESULT_TYPE_FAILED';

export const ADD_MEDICAL_TEST_REQUESTED = 'ADD_MEDICAL_TEST_REQUESTED';
export const ADD_MEDICAL_TEST_SUCESS = 'ADD_MEDICAL_TEST_SUCESS';
export const ADD_MEDICAL_TEST_FAILED = 'ADD_MEDICAL_TEST_FAILED';

export const OPEN_DIALOG_REQUESTED = 'OPEN_DIALOG_REQUESTED';

export const MEDICAL_TEST_BY_CATEGORY_REQUESTED = 'MEDICAL_TEST_BY_CATEGORY_REQUESTED';
export const MEDICAL_TEST_BY_CATEGORY_SUCESS = 'MEDICAL_TEST_BY_CATEGORY_SUCESS';
export const MEDICAL_TEST_BY_CATEGORY_FAILED = 'MEDICAL_TEST_BY_CATEGORY_FAILED';

export const DELETE_MEDICAL_TEST_REQUESTED = 'DELETE_MEDICAL_TEST_REQUESTED';
export const DELETE_MEDICAL_TEST_SUCESS = 'DELETE_MEDICAL_TEST_SUCESS';
export const DELETE_MEDICAL_TEST_FAILED = 'DELETE_MEDICAL_TEST_FAILED';

// Doctor ------------------------------------------

export const DOCTOR_PROFILES_REQUESTED = 'DOCTOR_PROFILES_REQUESTED';
export const DOCTOR_PROFILES_REQUESTED_SUCESS = 'DOCTOR_PROFILES_REQUESTED_SUCESS';
export const DOCTOR_PROFILES_REQUESTED_FAILED = 'DOCTOR_PROFILES_REQUESTED_FAILED';

export const DOCTOR_OPEN_DIALOG_REQUESTED = 'DOCTOR_OPEN_DIALOG_REQUESTED';

export const DOCTOR_HANDLE_INPUT_CHANGE = 'DOCTOR_HANDLE_INPUT_CHANGE';

export const DOCTOR_ADD_QUALIFICAION_REQUESTED = 'DOCTOR_ADD_QUALIFICAION_REQUESTED';
export const DOCTOR_ADD_QUALIFICAION_SUCESS = 'DOCTOR_ADD_QUALIFICAION_SUCESS';
export const DOCTOR_ADD_QUALIFICAION_FAILED = 'DOCTOR_ADD_QUALIFICAION_FAILED';

export const DOCTOR_ADD_SPECIALITY_REQUESTED = 'DOCTOR_ADD_SPECIALITY_REQUESTED';
export const DOCTOR_ADD_SPECIALITY_SUCESS = 'DOCTOR_ADD_SPECIALITY_SUCESS';
export const DOCTOR_ADD_SPECIALITY_FAILED = 'DOCTOR_ADD_SPECIALITY_FAILED';


// Subscriber------------------------------------------------------------------------------------

export const SUBSCRIBER_GET_ACTIVE_SUBSCRIPTIONS_REQUESTED = 'SUBSCRIBER_GET_ACTIVE_SUBSCRIPTIONS_REQUESTED';
export const SUBSCRIBER_GET_ACTIVE_SUBSCRIPTIONS_SUCESS = 'SUBSCRIBER_GET_ACTIVE_SUBSCRIPTIONS_SUCESS';
export const SUBSCRIBER_GET_ACTIVE_SUBSCRIPTIONS_FAILED = 'SUBSCRIBER_GET_ACTIVE_SUBSCRIPTIONS_FAILED';

export const SUBSCRIBER_HANDLE_INPUT_CHANGE = 'SUBSCRIBER_HANDLE_INPUT_CHANGE';

export const SUBSCRIBER_ASSIGN_ASSOCIATE_TO_SUBSCRIBER_REQUESTED = 'SUBSCRIBER_ASSIGN_ASSOCIATE_TO_SUBSCRIBER_REQUESTED';
export const SUBSCRIBER_ASSIGN_ASSOCIATE_TO_SUBSCRIBER_SUCESS = 'SUBSCRIBER_ASSIGN_ASSOCIATE_TO_SUBSCRIBER_SUCESS';
export const SUBSCRIBER_ASSIGN_ASSOCIATE_TO_SUBSCRIBER_FAILED = 'SUBSCRIBER_ASSIGN_ASSOCIATE_TO_SUBSCRIBER_FAILED';

export const SUBSCRIBER_GET_ALL_PRODUCTS_REQUESTED = 'SUBSCRIBER_GET_ALL_PRODUCTS_REQUESTED';
export const SUBSCRIBER_GET_ALL_PRODUCTS_SUCESS = 'SUBSCRIBER_GET_ALL_PRODUCTS_SUCESS';
export const SUBSCRIBER_GET_ALL_PRODUCTS_FAILED = 'SUBSCRIBER_GET_ALL_PRODUCTS_FAILED';