const tabledata=[
    {
      id:1,
      image:"images/Vector1.png",
      testName:"Pulse",
      minValue:60,
      maxValue:100,
      measurementUnit:"bpm",
      resultType:"Integer"
    },
    {
        id:2,
        image:"images/Vector1.png",
        testName:"Pulse",
        minValue:61,
        maxValue:100,
        measurementUnit:"bpm",
        resultType:"Integer"
      },  
      {
        id:3,
        image:"images/Vector1.png",
        testName:"Pulse",
        minValue:62,
        maxValue:100,
        measurementUnit:"bpm",
        resultType:"Integer"
      }, 
      {
        id:4,
        image:"images/Vector1.png",
        testName:"Pulse",
        minValue:63,
        maxValue:100,
        measurementUnit:"bpm",
        resultType:"Integer"
      },  
      {
      id:5,
      image:"images/Vector1.png",
      testName:"Pulse",
      minValue:64,
      maxValue:100,
      measurementUnit:"bpm",
      resultType:"Integer"
    },  
    {
        id:6,
        image:"images/Vector1.png",
        testName:"Pulse",
        minValue:65,
        maxValue:100,
        measurementUnit:"bpm",
        resultType:"Integer"
      },  
      {
        id:7,
        image:"images/Vector1.png",
        testName:"Pulse",
        minValue:66,
        maxValue:100,
        measurementUnit:"bpm",
        resultType:"Integer"
      },  
      {
        id:8,
        image:"images/Vector1.png",
        testName:"Pulse",
        minValue:67,
        maxValue:100,
        measurementUnit:"bpm",
        resultType:"Integer"
      },  
      {
        id:9,
        image:"images/Vector1.png",
        testName:"Pulse",
        minValue:68,
        maxValue:100,
        measurementUnit:"bpm",
        resultType:"Integer"
      },
      
  ]
 

  export default tabledata;